/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyPaintsRouteImport } from './routes/my-paints'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PaintsIndexRouteImport } from './routes/paints/index'
import { Route as PaintsPaintIdRouteImport } from './routes/paints/$paintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPaintsRoute = MyPaintsRouteImport.update({
  id: '/my-paints',
  path: '/my-paints',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintsIndexRoute = PaintsIndexRouteImport.update({
  id: '/paints/',
  path: '/paints/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintsPaintIdRoute = PaintsPaintIdRouteImport.update({
  id: '/paints/$paintId',
  path: '/paints/$paintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-paints': typeof MyPaintsRoute
  '/settings': typeof SettingsRoute
  '/paints/$paintId': typeof PaintsPaintIdRoute
  '/paints/': typeof PaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-paints': typeof MyPaintsRoute
  '/settings': typeof SettingsRoute
  '/paints/$paintId': typeof PaintsPaintIdRoute
  '/paints': typeof PaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-paints': typeof MyPaintsRoute
  '/settings': typeof SettingsRoute
  '/paints/$paintId': typeof PaintsPaintIdRoute
  '/paints/': typeof PaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-paints' | '/settings' | '/paints/$paintId' | '/paints/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-paints' | '/settings' | '/paints/$paintId' | '/paints'
  id:
    | '__root__'
    | '/'
    | '/my-paints'
    | '/settings'
    | '/paints/$paintId'
    | '/paints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyPaintsRoute: typeof MyPaintsRoute
  SettingsRoute: typeof SettingsRoute
  PaintsPaintIdRoute: typeof PaintsPaintIdRoute
  PaintsIndexRoute: typeof PaintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-paints': {
      id: '/my-paints'
      path: '/my-paints'
      fullPath: '/my-paints'
      preLoaderRoute: typeof MyPaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paints/': {
      id: '/paints/'
      path: '/paints'
      fullPath: '/paints/'
      preLoaderRoute: typeof PaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paints/$paintId': {
      id: '/paints/$paintId'
      path: '/paints/$paintId'
      fullPath: '/paints/$paintId'
      preLoaderRoute: typeof PaintsPaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyPaintsRoute: MyPaintsRoute,
  SettingsRoute: SettingsRoute,
  PaintsPaintIdRoute: PaintsPaintIdRoute,
  PaintsIndexRoute: PaintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
